<?php
class GlobalConstants {
	
	const CACHE_MADE = 'CACHE_MADE';
	
	const SESSION_PRODUCT_SEARCH_CRITERIA = "SESSION_PRODUCT_SEARCH_CRITERIA";
	const SESSION_CURR_PAGE = "SESSION_CURR_PAGE";
	
}