<?php
class GlobalConstants {
	
	const CACHE_MADE = 'CACHE_MADE';
	const CACHE_ROLE = 'CACHE_ROLE';
	
	const SESSION_SEARCH_CRITERIA = "SESSION_SEARCH_CRITERIA";
	const SESSION_PRODUCT_SEARCH_CRITERIA = "SESSION_PRODUCT_SEARCH_CRITERIA";
	const SESSION_CURR_PAGE = "SESSION_CURR_PAGE";
	const SESSION_DISPLAY_FORMAT = "SESSION_DISPLAY_FORMAT";
	
	const ROLE_ADMIN = "AD";
	const ROLE_SUPPLIER = "SU";
	
	const DISPLAY_FORMAT_EXCEL = "E";
	const DISPLAY_FORMAT_GRID = "G";
	
	const PRODUCE_STATUS_PREPARE = "PP";
	const PRODUCE_STATUS_BOOK = "BK";
	const PRODUCE_STATUS_MODELING = "MD";
	const PRODUCE_STATUS_CHECK = "CK";
	const PRODUCE_STATUS_EDIT = "ED";
	const PRODUCE_STATUS_PAUSE = "PA";
	const PRODUCE_STATUS_CANCEL = "CL";
	const PRODUCE_STATUS_MONOPOLY = "MO";
	const PRODUCE_STATUS_COMPLETE = "CP";
}
